# Generated by Django 6.0.1 on 2026-02-02 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='amount_gt_0',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_in_gbp',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='结算金额(GBP)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound (£)'), ('CNY', 'Chinese Yuan (¥)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='输入金额'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0)), name='amount_gt_0'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
    ]
