# Generated by Django 6.0.1 on 2026-02-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_transaction_amount_gt_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_in_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='结算金额(GBP)'),
        ),
    ]
