# Generated by Django 6.0.1 on 2026-03-14 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_alter_category_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "type", "occurred_at"],
                name="finance_tra_user_id_669e2a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "original_amount"],
                name="finance_tra_user_id_4a8768_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "amount_in_gbp"], name="finance_tra_user_id_6f4345_idx"
            ),
        ),
    ]
