# Generated by Django 6.0.1 on 2026-03-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_transaction_finance_tra_user_id_669e2a_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailotp",
            name="finance_ema_email_477bc6_idx",
        ),
        migrations.DeleteModel(
            name="EmailOTP",
        ),
    ]
